# Data paths
data_path: /home/ruslan/data/datasets_ssd/kaggle/petfinder-pawpularity-score/

# Model parameters
image_size: 384
model_params:
  model_name: swin_large_patch4_window12_384
  num_image_neurons: 256
  dropout: 0.6
  attn_drop: 0.1
regression_margin: 1.0

# Augmentation
dataset_args:
  replace_bg_prob: 0.01
  glob_crop_prob: 0.1
  pet_crop_prob: 0.1

# Training parameters
num_folds: 5
max_epochs: 8
batch_size: 10
learning_rate: 0.00002
mixup_proba: -1
random_seed: 42
freeze_augmentations: 2

# Hardware
cpus: 6
gpus: 1
