# Data paths
data_path: /home/ruslan/data/datasets_ssd/kaggle/petfinder-pawpularity-score/

# Training parameters
choose_categories: 'all'

# Model parameters
image_size: 224
regression_margin: 1.594
model_type: swin
swin_model_name: swin_base_patch4_window7_224
swin_num_image_neurons: 2000
swin_dropout_1: 0.436
swin_dropout_2: 0.640
swin_attn_drop: 0 #0.01968
swin_freeze_layers: 3

# Augmentation
freeze_augmentations: 4.85
replace_bg_prob: 0.19
glob_crop_prob: 0.4
pet_crop_prob: 0.2709
aug_brightness_lim: 0.136
aug_contrast_lim: 0.366
aug_hue_lim: 0.08
aug_sat_lim: 0.33
aug_val_lim: 0.22
aug_brcon_prob: 0.8
aug_hsv_prob: 0.63
aug_gray_prob: 0.11

# Muxip
mixup_proba: 0.5
mixup_alpha: 0.5

# Old domain
old_domain_prob: 0.0

# Loss
bce_weight: 0.67
hinge_margin: 12.315

# Predictions
prediction_lightness_delta: 0.083
prediction_pet_crop_weight: 0.6
prediction_glob_crop_weight: 0.4968

# Training parameters
num_folds: 10
max_epochs: 10
batch_size: 25
learning_rate: 0.00002878
weight_decay: 0.000463
mixup_proba: -1

# Hardware
cpus: 6
gpus: 1

# Run-type-specific
random_seed: 42
wandb_project: pf2