# Data paths
data_path: /home/ruslan/data/datasets_ssd/kaggle/petfinder-pawpularity-score/

# Training parameters
choose_categories: 'all'

# Model parameters
image_size: 224
regression_margin: 1.555
model_type: swin
swin_model_name: swin_base_patch4_window7_224
swin_num_image_neurons: 2000
swin_dropout_1: 0.4379
swin_dropout_2: 0.6277
swin_attn_drop: 0.03102
swin_freeze_layers: 3

# Augmentation
replace_bg_prob: 0.1964
glob_crop_prob: 0.4246
pet_crop_prob: 0.149
freeze_augmentations: 3.133

# Loss
bce_weight_cat: 0.6952
bce_weight_dog: 0.7165
hinge_margin: 13.961

# Predictions
prediction_lightness_delta: 0.08765
prediction_pet_crop_weight: 0.3061
prediction_glob_crop_weight: 0.5501

# Training parameters
num_folds: 10
max_epochs: 10
batch_size: 25
learning_rate: 0.00002704
weight_decay: 0.001183
mixup_proba: -1

# Hardware
cpus: 6
gpus: 1

# Run-type-specific
random_seed: 42
wandb_project: pf2