# Data paths
data_path: /home/ruslan/data/datasets_ssd/kaggle/petfinder-pawpularity-score/

# Model parameters
image_size: 224
model_params:
  model_name: swin_base_patch4_window7_224
  num_image_neurons: 256
  dropout: 0.5
  attn_drop: 0.1
regression_margin: 1.0

# Training parameters
num_folds: 5
max_epochs: 10
batch_size: 20
learning_rate: 0.00002
mixup_proba: -1
random_seed: 42
freeze_augmentations: 2